# Generated by Django 5.2.4 on 2025-07-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_appointment_proccedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
